apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brewz-xc-ingress
  annotations:
    # Load Balancer annotations
    ingress.cloud.f5.com/max-request-header-size: "90"
    ingress.cloud.f5.com/lb-method: random
    ingress.cloud.f5.com/max-fails: "5"
    ingress.cloud.f5.com/connection-timeout: "4000"
    ingress.cloud.f5.com/https-auto-cert: "false"   #TLS termination with auto cert
    ingress.cloud.f5.com/http-redirect: "false"     #Enable HTTP to HTTPs redirect
    ingress.cloud.f5.com/public-ip-address: ~{ (datasource "terraform").argocd_lb_ip_address }~ # Tenant Static IP Address

    # Load Balancer Route annotations
    ingress.cloud.f5.com/disable-host-rewrite: "nic-nginx-ingress-controller"

    # Origin Pool annotations
    ingress.cloud.f5.com/ssl-services: "nic-nginx-ingress-controller"

spec:
  tls:
    - hosts:
      - ~{ template "brewz_host" }~
      secretName: ~{ (datasource "terraform").xc_lb_lab_tls_secret_name }~
  rules:
    - host: ~{ template "brewz_host" }~
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nic-nginx-ingress-controller
                port:
                  number: 443
